# Generated by Django 4.2.29 on 2026-03-19 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_ip', models.GenericIPAddressField(default='0.0.0.0')),
                ('destination_ip', models.GenericIPAddressField(default='0.0.0.0')),
                ('protocol', models.CharField(default='tcp', max_length=10)),
                ('attack_type', models.CharField(max_length=50)),
                ('attack_category', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('high', 'High'), ('critical', 'Critical')], default='info', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('_raw_features', models.TextField(db_column='raw_features', default='{}')),
                ('_shap_explanation', models.TextField(db_column='shap_explanation', default='{}')),
                ('_top_features', models.TextField(db_column='top_features', default='[]')),
                ('_probabilities', models.TextField(db_column='probabilities', default='{}')),
                ('blockchain_block_index', models.IntegerField(blank=True, null=True)),
                ('blockchain_hash', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NetworkSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.TextField()),
                ('alert', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ids_app.alert')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
